### ISSUE TITLE
where is the 'checkpoints/RN50_imagenet.pth'

### ISSUE THREAD

**Issue by zhilingz** [jiamingzhang94/Unlearnable-Clusters#1]

**Comment by jiamingzhang94** [comment]
This is the path to the checkpoint of surrogate model. You can just use the pre-trained weights provided by torchvision, or train a model in Imagenet by yourself. The config is detailed in `config/stage_1.yaml`.

**Comment by jiamingzhang94** [comment]
Now, we have changed the way that loading weights from `checkpoints` folder to automatic download.
