### ISSUE TITLE
Can't find the module and function

### ISSUE THREAD

**Issue by zhangyisheng0629** [jiamingzhang94/Unlearnable-Clusters#2]
Hello, I ran the preprocess.py file, but the ruamel module and the utils.get_model function were not found. Can it be solved, thank you very much!

**Comment by jiamingzhang94** [comment]
Hi @zhangyisheng0629 , `ruamel ` is a python package, you can solve it by `pip install`. As for `get_model` funcation, you can rename it to `get_surrogate` to solve.
