### ISSUE TITLE
Implement detail question about train_gnet in main.py and Algorithm 1 in original paper

### ISSUE THREAD

**Issue by pppppkun** [jiamingzhang94/Unlearnable-Clusters#3]
In original paper, the line 9 of Algorithm 1 iter the images all in C_i to optim G. However, in Line 60 in main.py (function train_gnet), it is seem like iter all images in dataset.
Is there something wrong with my understanding of Algorithm 1, or am I missing some detail in the code?

**Comment by jiamingzhang94** [comment]
Hi @pppppkun , you are very observant. This is actually mentioned in section 4.1: "For each `\delta_i`, we repeated `p` times to train the generator `G` for entire datasets". In short, it is inspired by [1] that using more training data when training the generator of UAP can help to perform a better fit.

[1] Poursaeed, O., Katsman, I., Gao, B., & Belongie, S. (2018). Generative adversarial perturbations. In Proceedings of the IEEE conference on computer vision and pattern recognition (pp. 4422-4431).

**Comment by pppppkun** [comment]
Thank you very much for your answer!
